/** * This code was generated by Builder.io. */ import { NgModule } from
"@angular/core"; import { CommonModule } from "@angular/common"; import {
Component } from "@angular/core"; @Component({ selector: "my-component,
MyComponent", template: `
<div
  class="text-white text-base font-bold leading-5 whitespace-nowrap justify-center items-stretch bg-black pt-3 pb-2.5 px-4 rounded-md"
>
  Inscribir
</div>
`, }) export class MyComponent {} @NgModule({ declarations: [MyComponent],
imports: [CommonModule], exports: [MyComponent], }) export class
MyComponentModule {}
